name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.10"] # 3.5, 3.6, 3.7, 

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3

        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3 # changes this to v3 from v2 for same node12 node16 error
        with:
          python-version: ${{ matrix.python-version }}
        
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
    
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          channels: conda-forge
          channel-priority: true
          python-version: "3.10"
          environment-file: environment.yml
          mamba-version: "*"
          auto-activate-base: false
          use-mamba: true
      - run: |
          conda info
          conda list

      - name: Run tests
        run: pytest tests.py